"""update the database to fix the failing tests

Revision ID: 4211a0319756
Revises: 52a401750a76
Create Date: 2024-09-25 07:37:55.147483

"""
from alembic import op
import sqlalchemy as sa
from core import db

from core.apis.decorators import AuthPrincipal
from core.models.assignments import Assignment

# revision identifiers, used by Alembic.
revision = '4211a0319756'
down_revision = '52a401750a76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    Assignment.mark_grade(
        _id=4,
        grade="D",
        auth_principal=AuthPrincipal(user_id=4, teacher_id=2)
    )
    db.session.commit()
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    db.session.execute("""UPDATE assignments
    SET state='SUBMITTED', grade=NULL
    WHERE id=4""")
    db.session.commit()
    # ### end Alembic commands ###
